# Generated by Django 4.1.5 on 2023-01-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, null=True, verbose_name='ФИО сотрудника')),
                ('position', models.CharField(max_length=100, null=True, verbose_name='Должность сотрудника')),
                ('Date_of_employment', models.DateField(default='2023:01:31')),
                ('Salary_amount', models.IntegerField(blank=True, default=0, null=True, verbose_name='Размер заработной платы')),
                ('photo', models.ImageField(blank=True, upload_to='images/elements', verbose_name='Фото сотрудника')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
