# Generated by Django 4.1.5 on 2023-01-31 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Должность сотрудника')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Salary_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Date_of_employment',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='fio',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='position',
        ),
        migrations.AddField(
            model_name='user',
            name='fk_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Staff.position', verbose_name='Должность сотрудника'),
        ),
    ]
