# Generated by Django 4.1.5 on 2023-01-31 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0002_position_rename_salary_amount_user_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateField(default='31.01.2023', verbose_name='Дата приёма на работу'),
        ),
    ]
